name: Send mailer

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # You may pin to the exact commit or the version.
  # uses: devellany/send-mail@45dbe31722b9c29635bc9d60315d420218093c56
uses: devellany/send-mail@v1.0.2
with:
  # Enter SMTP host.
  host:
  # Enter SMTP port. (defaults to 465)
  port:
    # Enter SMTP host account.
  account:
    # Enter SMTP host account password.
  password:
    # Enter sender name.
  sender:
    # Enter sender mail.
  from:
    # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
  to:
    # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
  subject:
    # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
  body:
    # Enter Content-Type HTTP header. (defaults to 'text/plain')
  contentType:
    # Attachment files are entered as an array. Required key 'path'. (The prefix 'file://' if you want to read a file)
  attachments: # optional
